#!/bin/bash

ANDROID_BUILD_TOP="$(dirname $(realpath "$0"))"
CHECK="$(echo $1 | grep -q check && echo 1)"
GERRIT_USERNAME="$(git config review.review.lineageos.org.username)"

function repopick() {
    if [[ "$CHECK" = "1" ]]; then
        echo -n "${@: -1} - " ; ssh lineage-gerrit gerrit query ${@: -1} --format=JSON | jq --slurp -r '.[0].status'
    else
        ${ANDROID_BUILD_TOP}/vendor/lineage/build/tools/repopick.py \
            -g "ssh://$GERRIT_USERNAME@review.lineageos.org:29418" $@ &
    fi
}

function repopickchain() {
    if [[ "$CHECK" = "1" ]]; then
        echo -n "$1 - " ; ssh lineage-gerrit gerrit query $1 --format=JSON | jq --slurp -r '.[0].status'
    else
        `${ANDROID_BUILD_TOP}/gen_chain $@`
    fi
}

function rc() {
    echo `${ANDROID_BUILD_TOP}/gen_chain $@ | cut -b10-`
}

apply_patch() {
    echo -e "${GREEN}Applying patch...${NOCOLOR}"
    echo -e "${LIGHTBLUE}Target repo:${NOCOLOR} $1"
    echo -e "${LIGHTBLUE}Patch file:${NOCOLOR} $2"

    if [ -d "$ANDROID_BUILD_TOP/$1" ] && [ -f "$2" ]; then
        cd "$1"
        git am -3 --ignore-whitespace "$2"
        cd "$ANDROID_BUILD_TOP" && echo ""
    else
        echo "Can't find dir $1 or patch file $2, skipping patch"
    fi
}


apply_patch_recursive() {
    echo -e "${GREEN}Applying patches recursively...${NOCOLOR}"
    echo -e "${LIGHTBLUE}Target directory:${NOCOLOR} $1"
    echo -e "${LIGHTBLUE}Patch directory:${NOCOLOR} $2"

    # Check if the target and patch directories exist
    if [ ! -d "$ANDROID_BUILD_TOP/$1" ]; then
        echo "Target directory $1 not found, exiting."
        return 1
    fi

    if [ ! -d "$2" ]; then
        echo "Patch directory $2 not found, exiting."
        return 1
    fi

    # Iterate over each .patch file in the patch directory
    for patch_file in "$2"/*.patch; do
        if [ -f "$patch_file" ]; then
            # Call apply_patch for each .patch file
            apply_patch "$1" "$patch_file"
        else
            echo "No .patch files found in $2, skipping."
        fi
    done
}

#
# _examples_
#
# # repo/1
# changes=(
#     2137 # hello
#     `rc 2137` # hello (chain)
# )
# repopick ${changes[@]}
#
# # repo/2
# repopickchain 2137 # hello (chain)
#
# # repo/3
# repopick 2137 # hello
#

# build/make
repopick -f 332045 # Don't enforce vintf kernel requirements when building without LTO

# frameworks/base
repopick -f 357988 # Set DEFAULT_ADB_ALLOWED_CONNECTION_TIME to 0

# packages/apps/Trebuchet
repopick 407612 # Trebuchet: Eleven -> Twelve

# vendor/lineage
repopick 407581 # common: Eleven -> Twelve

wait
